services:
  - type: web
    name: syncplay
    runtime: node
    plan: free
    buildCommand: npm install && npm install --prefix client && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
